version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "UTC"
    groups:
      ai-providers:
        patterns:
          - "openai"
          - "anthropic"
          - "google-genai"
          - "langchain-core"
          - "langchain-community"
          - "langchain-openai"
          - "langchain-anthropic"
          - "langgraph"
    allow:
      - dependency-name: "openai"
      - dependency-name: "anthropic"
      - dependency-name: "google-genai"
      - dependency-name: "langchain-core"
      - dependency-name: "langchain-community"
      - dependency-name: "langchain-openai"
      - dependency-name: "langchain-anthropic"
      - dependency-name: "langgraph"
    open-pull-requests-limit: 1
    reviewers:
      - "PostHog/team-llm-analytics"
    # Uncomment below to enable auto-merge for minor updates when CI passes
    # pull-request-branch-name:
    #   separator: "/"
    # assignees:
    #   - "PostHog/ai-team"
